/**
 * Ключевые слова p5.js для подсветки синтаксиса в CodeMirror 6
 * Основано на официальной документации p5.js Reference
 * @see https://p5js.org/reference/
 */

// Структурные функции
export const STRUCTURE_FUNCTIONS = [
  'setup',
  'draw',
  'preload',
  'mousePressed',
  'mouseDragged',
  'mouseMoved',
  'mouseReleased',
  'mouseClicked',
  'mouseWheel',
  'doubleClicked',
  'touchStarted',
  'touchMoved',
  'touchEnded',
  'keyPressed',
  'keyReleased',
  'keyTyped',
  'keyCode',
  'keyIsPressed',
  'windowResized',
  'remove',
  'noLoop',
  'loop',
  'push',
  'pop',
  'redraw',
]

// Функции рисования 2D примитивов
export const SHAPE_FUNCTIONS = [
  'arc',
  'ellipse',
  'line',
  'point',
  'quad',
  'rect',
  'square',
  'circle',
  'triangle',
  'curve',
  'curveTightness',
  'curvePoint',
  'curveTangent',
  'curveDetail',
  'beginContour',
  'endContour',
  'beginShape',
  'endShape',
  'vertex',
  'bezierVertex',
  'quadraticVertex',
  'curveVertex',
  'rectMode',
  'ellipseMode',
  'strokeCap',
  'strokeJoin',
  'strokeWeight',
]

// Функции работы с цветом
export const COLOR_FUNCTIONS = [
  'background',
  'clear',
  'color',
  'colorMode',
  'fill',
  'noFill',
  'stroke',
  'noStroke',
  'alpha',
  'blue',
  'brightness',
  'green',
  'hue',
  'lerpColor',
  'lightness',
  'red',
  'saturation',
]

// Константы цветов
export const COLOR_CONSTANTS = [
  'WHITE',
  'BLACK',
  'RED',
  'GREEN',
  'BLUE',
  'YELLOW',
  'CYAN',
  'MAGENTA',
  'ORANGE',
  'PINK',
  'PURPLE',
  'VIOLET',
  'GRAY',
  'GREY',
  'ALL',
  'ALT',
  'BACKSPACE',
  'CONTROL',
  'DELETE',
  'DOWN_ARROW',
  'ENTER',
  'ESCAPE',
  'LEFT_ARROW',
  'OPTION',
  'RETURN',
  'RIGHT_ARROW',
  'SHIFT',
  'TAB',
  'UP_ARROW',
  'BOLD',
  'ITALIC',
  'NORMAL',
  'LANDSCAPE',
  'PORTRAIT',
  'DEGREES',
  'RADIANS',
  'CORNER',
  'CORNERS',
  'RADIUS',
  'RIGHT',
  'LEFT',
  'CENTER',
  'TOP',
  'BOTTOM',
  'BASELINE',
  'POSITIVE',
  'NEGATIVE',
  'CLOSE',
  'OPEN',
  'CHORD',
  'PIE',
  'PROJECT',
  'SQUARE',
  'ROUND',
  'BEVEL',
  'MITER',
  'RGB',
  'HSB',
  'HSL',
]

// Функции работы с изображениями
export const IMAGE_FUNCTIONS = [
  'createImage',
  'save',
  'saveCanvas',
  'saveFrames',
  'loadImage',
  'image',
  'imageMode',
  'tint',
  'noTint',
  'blendMode',
  'blend',
  'copy',
  'filter',
  'get',
  'set',
  'pixels',
  'updatePixels',
  'loadPixels',
  'loadShader',
  'shader',
  'resetShader',
  'texture',
  'textureMode',
  'textureWrap',
  'createTexture',
]

// Функции трансформации
export const TRANSFORM_FUNCTIONS = [
  'applyMatrix',
  'resetMatrix',
  'rotate',
  'rotateX',
  'rotateY',
  'rotateZ',
  'scale',
  'shearX',
  'shearY',
  'translate',
  'pushMatrix',
  'popMatrix',
  'printMatrix',
]

// Функции работы с данными
export const DATA_FUNCTIONS = [
  'dist',
  'max',
  'min',
  'nf',
  'nfc',
  'nfp',
  'nfs',
  'constrain',
  'abs',
  'ceil',
  'exp',
  'floor',
  'lerp',
  'log',
  'mag',
  'map',
  'mod',
  'norm',
  'pow',
  'round',
  'sq',
  'sqrt',
  'fract',
  'deg',
  'rad',
  'sin',
  'cos',
  'tan',
  'asin',
  'acos',
  'atan',
  'atan2',
  'random',
  'randomGaussian',
  'randomSeed',
  'noise',
  'noiseSeed',
  'noiseDetail',
  'noiseMode',
  'randomUnit',
]

// Функции работы с массивами
export const ARRAY_FUNCTIONS = [
  'append',
  'arrayCopy',
  'concat',
  'reverse',
  'shorten',
  'shuffle',
  'sort',
  'splice',
  'subset',
  'float',
  'int',
  'str',
  'boolean',
  'byte',
  'char',
  'unchar',
  'hex',
  'unhex',
  'join',
  'split',
  'splitTokens',
  'trim',
  'indexOf',
  'search',
  'match',
  'matchAll',
]

// Функции DOM (Document Object Model)
export const DOM_FUNCTIONS = [
  'createCanvas',
  'createGraphics',
  'createDiv',
  'createP',
  'createSpan',
  'createImg',
  'createA',
  'createSlider',
  'createButton',
  'createCheckbox',
  'createSelect',
  'createRadio',
  'createColorPicker',
  'createInput',
  'createFileInput',
  'createVideo',
  'createAudio',
  'createCapture',
  'createElement',
  'select',
  'selectAll',
  'removeElements',
  'captureMouse',
  'captureTouch',
  'captureClick',
  'captureWheel',
  'captureKey',
]

// Функции среды
export const ENVIRONMENT_FUNCTIONS = [
  'width',
  'height',
  'pixelDensity',
  'displayDensity',
  'getURL',
  'getUrlPath',
  'getParams',
  'frameCount',
  'focused',
  'cursor',
  'noCursor',
  'frameRate',
  'displayWidth',
  'displayHeight',
  'windowWidth',
  'windowHeight',
  'windowX',
  'windowY',
  'deviceOrientation',
  'accelerationX',
  'accelerationY',
  'accelerationZ',
  'pAccelerationX',
  'pAccelerationY',
  'pAccelerationZ',
  'rotationX',
  'rotationY',
  'rotationZ',
  'pRotationX',
  'pRotationY',
  'pRotationZ',
  'turnAxis',
  'touches',
  'mouseX',
  'mouseY',
  'pmouseX',
  'pmouseY',
  'mouseButton',
  'mouseIsPressed',
  'key',
  'keyIsPressed',
  'keyCode',
  'moveX',
  'moveY',
  'moveZ',
  'rotation',
  'scaleX',
  'scaleY',
  'scaleZ',
  'centerX',
  'centerY',
  'centerZ',
  'axis',
  'debugMode',
  'noDebugMode',
  'setAttributes',
  'pixelDensity',
]

// Функции работы со шрифтами и текстом
export const TYPOGRAPHY_FUNCTIONS = [
  'loadFont',
  'text',
  'textFont',
  'textAlign',
  'textLeading',
  'textSize',
  'textStyle',
  'textWidth',
  'textAscent',
  'textDescent',
  'textWrap',
  'leading',
  'textBounds',
  'textToPoints',
  'opentype',
]

// Функции 3D
export const WEBGL_FUNCTIONS = [
  'box',
  'sphere',
  'cylinder',
  'cone',
  'ellipsoid',
  'torus',
  'plane',
  'normalMaterial',
  'texture',
  'ambientLight',
  'directionalLight',
  'pointLight',
  'spotLight',
  'lightFalloff',
  'lights',
  'noLights',
  'shininess',
  'specularColor',
  'emissiveColor',
  'camera',
  'perspective',
  'ortho',
  'orbitControl',
  'arc',
  'ellipse',
  'line',
  'plane',
  'point',
  'quad',
  'rect',
  'triangle',
  'model',
  'loadModel',
  'loadShader',
  'shader',
  'uniforms',
  'createFramebuffer',
]

// Функции ввода
export const INPUT_FUNCTIONS = [
  'keyIsDown',
  'createInput',
  'createButton',
  'createSlider',
  'createCheckbox',
  'createSelect',
  'createRadio',
  'createColorPicker',
  'createFileInput',
  'accelerationX',
  'accelerationY',
  'accelerationZ',
  'deviceMoved',
  'deviceTurned',
  'deviceShaken',
  'keyIsPressed',
  'prompt',
  'alert',
  'confirm',
]

// Функции времени
export const TIME_FUNCTIONS = [
  'millis',
  'seconds',
  'minute',
  'hour',
  'day',
  'month',
  'year',
]

// Функции сохранения/загрузки
export const IO_FUNCTIONS = [
  'loadJSON',
  'loadStrings',
  'loadTable',
  'loadXML',
  'httpGet',
  'httpPost',
  'httpDo',
  'save',
  'saveJSON',
  'saveStrings',
  'saveTable',
  'selectFolder',
  'selectInput',
  'selectOutput',
  'parseJSON',
  'createWriter',
  'createReader',
]

// Объекты
export const OBJECTS = [
  'p5',
  'p5.Element',
  'p5.Graphics',
  'p5.Vector',
  'p5.Color',
  'p5.Image',
  'p5.Table',
  'p5.TableRow',
  'p5.XML',
  'p5.Font',
  'p5.Geometry',
  'p5.Matrix',
  'p5.Renderer',
  'p5.Shader',
  'p5.Texture',
  'p5.MediaElement',
  'p5.Video',
  'p5.AudioIn',
  'p5.AudioOut',
  'p5.SoundFile',
  'p5.Amplitude',
  'p5.FFT',
  'p5.PeakDetect',
  'p5.Reverb',
  'p5.Convolver',
  'p5.Phrase',
  'p5.Part',
  'p5.Score',
  'p5.Oscillator',
  'p5.Noise',
  'p5.Pulse',
  'p5.SinOsc',
  'p5.TriOsc',
  'p5.SqrOsc',
  'p5.SawOsc',
  'p5.Env',
  'p5.Filter',
  'p5.EQ',
  'p5.Compressor',
  'p5.SoundRecorder',
  'p5.Panner',
  'p5.Listener3D',
  'p5.Meter',
  'p5.Distortion',
  'p5.Gain',
  'p5.Delay',
  'p5.OnsetDetect',
  'Number',
  'String',
  'Boolean',
  'Array',
  'Object',
  'Date',
  'Math',
  'RegExp',
  'JSON',
  'Map',
  'Set',
]

// Классы для создания объектов
export const CLASSES = [
  'createVector',
  'createColor',
  'createImage',
  'createGraphics',
  'createFont',
  'createMatrix',
  'createShader',
  'createFramebuffer',
]

// Объединяем все ключевые слова
export const P5_KEYWORDS = [
  ...STRUCTURE_FUNCTIONS,
  ...SHAPE_FUNCTIONS,
  ...COLOR_FUNCTIONS,
  ...COLOR_CONSTANTS,
  ...IMAGE_FUNCTIONS,
  ...TRANSFORM_FUNCTIONS,
  ...DATA_FUNCTIONS,
  ...ARRAY_FUNCTIONS,
  ...DOM_FUNCTIONS,
  ...ENVIRONMENT_FUNCTIONS,
  ...TYPOGRAPHY_FUNCTIONS,
  ...WEBGL_FUNCTIONS,
  ...INPUT_FUNCTIONS,
  ...TIME_FUNCTIONS,
  ...IO_FUNCTIONS,
  ...OBJECTS,
  ...CLASSES,
]

// Убираем дубликаты и сортируем
export const UNIQUE_P5_KEYWORDS = [...new Set(P5_KEYWORDS)].sort()
